jobs:
  include:
    - stage: test
      language: python
      python:
        - "3.6"
      install:
        - pip install -r "backend/requirements.txt"
      script:
        - python -m py_compile "backend/endpoint.py"

    - stage: test
      language: node_js
      node_js:
        - "8"
      cache:
        directories:
          - "frontend/node_modules"
          - "frontend/.awcache"
      before_install:
        - cd frontend
      script:
        - npm run build
